package studentmanagement.model;

import java.util.Random;

public record Course(String name, String award, int courseCode, int durationYears, int totalCredits,
                     String department, boolean isFullTime) {
    private static final Random RAND = new Random();
    private static final Course[] COURSES = {
            new Course("Bachelor of Arts", "BA", 100, 3, 180,
                    "Arts and Humanities", true),
            new Course("Bachelor of Music", "BMus", 101, 3, 180,
                    "Music", true),
            new Course("Psychology", "BA", 102, 3, 180,
                    "Psychology", true),
            new Course("Media Studies", "BA", 103, 3, 180,
                    "Media Studies", true),
            new Course("Creative Writing and English", "BA", 104, 3,
                    180, "English", true),
            new Course("Bachelor of Social Science", "BSocSc", 105, 3,
                    180, "Social Sciences", true),
            new Course("Bachelor of Social Science (Community and Youth Work)", "BSocSc",
                    106, 3, 180, "Applied Social Studies", true),
            new Course("Applied Social Studies", "BA", 107, 3, 180,
                    "Applied Social Studies", true),
            new Course("Bachelor of Education (Primary Teaching)", "BEd", 108,
                    4, 240, "Education", true),
            new Course("Bachelor of Education (Primary Teaching - Gaeltacht)", "BEd", 109,
                    4, 240, "Education", true),
            new Course("Early Childhood Teaching and Learning", "BA", 110, 3,
                    180, "Education", true),
            new Course("Bachelor of Science", "BSc", 111, 4, 240,
                    "Science", true),
            new Course("Biotechnology", "BSc", 112, 4, 240,
                    "Biology", true),
            new Course("Biological and Geographical Sciences", "BSc", 113, 4,
                    240, "Biology and Geography", true),
            new Course("Physics with Astrophysics", "BSc", 114, 4,
                    240, "Physics", true),
            new Course("Biomedical Science", "BSc", 115, 4, 240,
                    "Biology", true),
            new Course("Theoretical Physics and Mathematics", "BSc", 116, 4,
                    240, "Physics and Mathematics", true),
            new Course("Data Science", "BSc", 117, 4, 240,
                    "Computer Science", true),
            new Course("Psychology", "BSc", 118, 4, 240,
                    "Psychology", true),
            new Course("Pharmaceutical and Biomedical Chemistry", "BSc", 119,
                    4, 240, "Chemistry", true),
            new Course("Mathematics (with Education)", "BSc", 120, 4,
                    240, "Mathematics and Education", true),
            new Course("Mathematics and Computer Science (with Education)", "BSc", 121,
                    4, 240, "Mathematics, Computer Science and Education", true),
            new Course("Science (with Education)", "BSc", 122, 4,
                    240, "Science and Education", true),
            new Course("Sport Science and Health", "BSc", 123, 4,
                    240, "Sport Science", true),
            new Course("Food Science and Human Nutrition", "BSc", 124, 4,
                    240, "Food Science", true),
            new Course("Computational Thinking", "BSc", 125, 4, 240,
                    "Computer Science", true),
            new Course("Multimedia, Mobile and Web Development", "BSc", 126, 4,
                    240, "Computer Science", true),
            new Course("Bachelor of Engineering", "BE", 127, 4, 240,
                    "Engineering", true),
            new Course("Robotics and Intelligent Devices", "BE", 128, 4,
                    240, "Engineering", true),
            new Course("Product Design and Innovation", "BE", 129, 4,
                    240, "Design and Innovation", true),
            new Course("Accounting and Finance", "BBS", 130, 3, 180,
                    "Business", true),
            new Course("Quantitative Finance", "BBS", 131, 4, 240,
                    "Business and Mathematics", true),
            new Course("Economics", "BBS", 132, 3, 180,
                    "Economics", true),
            new Course("BA International Economics", "BA", 133, 4,
                    240, "Economics", true),
            new Course("Business and Management", "BBS", 134, 3,
                    180, "Business", true),
            new Course("Business Management and Global Cultures", "BBS", 135,
                    3, 180, "Business", true),
            new Course("International Business", "BBS", 136, 3, 180,
                    "Business", true),
            new Course("International Business and Global Cultures", "BBS", 137,
                    3, 180, "Business", true),
            new Course("Marketing", "BBS", 138, 3, 180,
                    "Business", true),
            new Course("Marketing and Global Cultures", "BBS", 139, 3,
                    180, "Business", true),
            new Course("Business and Accounting", "BBS", 140, 3,
                    180, "Business", true),
            new Course("Finance", "BBS", 141, 3, 180,
                    "Business", true),
            new Course("Business with Sport Science", "BSc", 142, 4,
                    240, "Business and Sport Science", true),
            new Course("Accounting, Finance and German Studies", "BBA", 143,
                    4, 240, "Business and Languages", true),
            new Course("Accounting, Finance and Spanish & Latin American Studies", "BBA",
                    144, 4, 240, "Business and Languages", true),
            new Course("Business Management and Chinese Studies", "BBA", 145,
                    4, 240, "Business and Languages", true),
            new Course("Business Management and French Studies", "BBA", 146,
                    4, 240, "Business and Languages", true),
            new Course("Business Management and German Studies", "BBA", 147,
                    4, 240, "Business and Languages", true),
            new Course("Business Management and Spanish & Latin American Studies", "BBA",
                    148, 4, 240, "Business and Languages", true),
            new Course("International Business and Chinese Studies", "BBA", 149,
                    4, 240, "Business and Languages", true),
            new Course("International Business and French Studies", "BBA", 150,
                    4, 240, "Business and Languages", true),
            new Course("International Business and German Studies", "BBA", 151,
                    4, 240, "Business and Languages", true),
            new Course("International Business and Spanish & Latin American Studies", "BBA",
                    152, 4, 240, "Business and Languages", true),
            new Course("Marketing and Chinese Studies", "BBA", 153, 4,
                    240, "Business and Languages", true),
            new Course("Marketing and French Studies", "BBA", 154, 4,
                    240, "Business and Languages", true),
            new Course("Marketing and German Studies", "BBA", 155, 4,
                    240, "Business and Languages", true),
            new Course("Marketing and Spanish & Latin American Studies", "BBA", 156,
                    4, 240, "Business and Languages", true),
            new Course("Bachelor of Laws", "LLB", 157, 3, 180,
                    "Law", true),
            new Course("Law and Accounting", "BCL", 158, 3, 180,
                    "Law", true),
            new Course("Law and Arts", "BCL", 159, 3, 180,
                    "Law", true),
            new Course("Law and Business", "BCL", 160, 3, 180,
                    "Law", true),
            new Course("Law and Criminology", "BCL", 161, 3, 180,
                    "Law and Criminology", true),
            new Course("Law and Languages", "BCL", 162, 3, 180,
                    "Law and Languages", true),
            new Course("Criminology", "BA", 163, 3, 180,
                    "Criminology", true),
            new Course("Bachelor of Science General Nursing", "BSc", 164, 4,
                    240, "Nursing", true)
    };

    public static Course randomCourse() {
        return COURSES[RAND.nextInt(COURSES.length)];
    }

    public static Course containsCourse(String c) {
        for(Course course : COURSES) {
            if(course.name().equals(c)) return course;
        }
        return null;
    }
}